# Generated by Django 5.2.5 on 2025-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_in',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sign_in',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
