# Generated by Django 5.2.5 on 2025-09-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_sign_in_email_address_sign_in_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_in',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sign_in',
            name='jambscore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sign_in',
            name='email_address',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
