# Generated by Django 5.2.5 on 2025-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_sign_in_age_sign_in_jambscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_in',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
